---
# raspberry pi3 play file
- hosts: all
  become: true
  become_method: sudo
  remote_user: pi
  roles:
    - { role: common, tags: ['common'] }
    - { role: network, tags: ['network'] }
    - { role: webapp, tags: ['webapp'] }
    - common
    - network
    - webapp
  vars:
    panda: hungry
