- name: copy usb-motion.bash to ~/usb-motion.bash
  copy:
    src: usb-motion.bash
    dest: "/home/{{main_user}}"
    owner: "{{main_user}}"
    group: "{{main_user}}"
    mode: 0755

- name: copy 88-local.rules to /etc/udev/rules.d
  copy:
    src: 88-local.rules
    dest: /etc/udev/rules.d
    owner: root
    group: root
    mode: 0644

- name: activate udev rules
  command: sh -c "udevadm control --reload-rules"
