- include: dnsmasq.yml
- include: hostapd.yml

- name: Disable DHCP for wlan0
  copy:
    src: dhcpcd.conf
    dest: /etc/dhcpcd.conf
    owner: root
    group: root
    mode: 0644

# TODO Move up interface config before dhcpcd.conf
- name: Static IP Address configuration
  template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Set up IPV4 Forwarding so that device connected to pi via wlan0 can use wlan1
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: Activate IP Forwarding
  command: sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

# TODO Test if this works as expected
- name: Allow wifi clients to access to internet via wlan1
  command: "{{item}}"
  with_items:
    - bash -c "iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE"
    - bash -c "iptables -A FORWARD -i wlan1 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
    - bash -c "iptables -A FORWARD -i wlan0 -o wlan1 -j ACCEPT"

- name: Save iptables in file so the config is applied every time we reboot the Pi
  command: sh -c "iptables-save > /etc/iptables.ipv4.nat"

- name: Configure rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0644